export interface Source {
  readonly id: number
  readonly stage: string
  readonly title: string
  readonly url: string
  readonly oneLiner: string
  readonly lang: 'en' | 'cn'
  readonly insight: string
  readonly scene: string
}

export const SOURCES: readonly Source[] = [
  // ── PG 早期经典 ──
  {
    id: 1,
    stage: 'PG经典',
    title: 'How to Get Startup Ideas',
    url: 'https://paulgraham.com/startupideas.html',
    oneLiner: '经典的找想法方法论：从自己的问题出发',
    lang: 'en',
    insight: '好的创业想法不是想出来的，而是注意到的。刻意brainstorm会产生听起来合理但实际很差的想法。',
    scene: '你正在试图"想一个创业点子"',
  },
  {
    id: 2,
    stage: 'PG经典',
    title: 'Do Things That Don\'t Scale',
    url: 'https://paulgraham.com/ds.html',
    oneLiner: '早期不需要规模化，手动服务10个用户',
    lang: 'en',
    insight: '不是产品要做得极好，而是用户体验要极好。10%周增长4年后=200万用户。',
    scene: '你觉得手动做太慢了要先把产品做好',
  },
  {
    id: 3,
    stage: 'PG经典',
    title: 'Growth',
    url: 'https://paulgraham.com/growth.html',
    oneLiner: '创业和小生意的唯一区别是增长率',
    lang: 'en',
    insight: 'YC标准：5-7%周增长=好，10%=优秀，1%=还没找到方向。5%周增长4年后月收入$25M。',
    scene: '你不确定自己在做的是创业还是小生意',
  },
  // ── YC 现在 ──
  {
    id: 4,
    stage: 'YC',
    title: 'YC Request for Startups',
    url: 'https://www.ycombinator.com/rfs',
    oneLiner: 'YC觉得什么问题值得做',
    lang: 'en',
    insight: 'YC官方列出的他们认为值得解决的问题方向，每年更新。',
    scene: '你在找方向，想知道什么问题足够大',
  },
  {
    id: 5,
    stage: 'YC',
    title: 'YC RFS × Indie Hacker 视角',
    url: 'https://superframeworks.com/articles/yc-rfs-startup-ideas-indie-hackers-2026',
    oneLiner: '8个方向拆解成独立开发者可以切入的具体产品形态',
    lang: 'en',
    insight: 'YC的8个方向中，独立开发者能做的部分。',
    scene: '你是solo builder想知道YC的大方向里你能做什么',
  },
  // ── 从0到1 ──
  {
    id: 6,
    stage: '从0到1',
    title: 'Sam Altman - Startup Playbook',
    url: 'https://playbook.samaltman.com/',
    oneLiner: '从想法到规模化',
    lang: 'en',
    insight: '99%的创业公司死于自杀而不是谋杀。慢的创始人从来不会成功。',
    scene: '你在做创业的整体规划',
  },
  {
    id: 7,
    stage: '从0到1',
    title: 'YC Library',
    url: 'https://www.ycombinator.com/library',
    oneLiner: 'YC统一搜索入口',
    lang: 'en',
    insight: 'YC全部文章/视频/播客，可按fundraising/product/growth等分类搜索。',
    scene: '你有一个具体问题想找YC的建议',
  },
  {
    id: 8,
    stage: '从0到1',
    title: 'indie-dev-toolkit',
    url: 'https://github.com/thedaviddias/indie-dev-toolkit',
    oneLiner: '独立开发者工具清单，从支付到部署到营销到分析',
    lang: 'en',
    insight: '精选的独立开发者工具清单，全流程覆盖。',
    scene: '你在选技术栈/工具',
  },
  {
    id: 9,
    stage: '从0到1',
    title: 'Product Hunt 发布实操手册',
    url: 'https://www.demandcurve.com/playbooks/product-hunt-launch',
    oneLiner: 'PH发布实操手册',
    lang: 'en',
    insight: 'Demand Curve的PH发布完整操作手册，含时间线和前3小时策略。',
    scene: '你准备在Product Hunt上发布',
  },
  {
    id: 10,
    stage: '从0到1',
    title: 'PH Launch Checklist 2026',
    url: 'https://calmops.com/indie-hackers/product-hunt-launch-guide/',
    oneLiner: 'PH发布实操手册2',
    lang: 'en',
    insight: '2026最新PH算法变化和发布策略。',
    scene: '你想知道PH最新的规则和玩法',
  },
  // ── 融资 ──
  {
    id: 11,
    stage: '融资',
    title: 'YC SAFE 官方文档',
    url: 'https://www.ycombinator.com/documents',
    oneLiner: 'Post-money SAFE模板，2025年90%的pre-seed用这个',
    lang: 'en',
    insight: '2025年Q1数据：90%的pre-seed和64%的seed用SAFE而不是priced round。',
    scene: '你准备融资，需要法律文档模板',
  },
  {
    id: 12,
    stage: '融资',
    title: 'Cooley GO SAFE 生成器',
    url: 'https://www.cooleygo.com/documents/y-combinator-safe-financing-document-generator/',
    oneLiner: '生成安全融资文件，没有中国的有美国英国新加坡，有点差评',
    lang: 'en',
    insight: '在线填写参数自动生成SAFE文档，支持US/UK/Singapore。',
    scene: '你需要快速生成一份SAFE文档',
  },
  {
    id: 13,
    stage: '融资',
    title: 'Startup Starter Pack',
    url: 'https://github.com/Ro5s/Startup-Starter-Pack',
    oneLiner: '里面整理了很多机构的条款，很全很全',
    lang: 'en',
    insight: '开源法律文档：SAFE/Term Sheet/顾问协议/员工协议等。',
    scene: '你需要各种创业法律文档模板',
  },
  {
    id: 14,
    stage: '融资',
    title: 'Carta - Term Sheet 详解',
    url: 'https://carta.com/learn/startups/fundraising/term-sheets/',
    oneLiner: 'Term sheet每一条都什么意思',
    lang: 'en',
    insight: 'Term sheet每一个条款的解释，从创始人视角说明哪些要警惕。',
    scene: '你收到了term sheet但看不懂某些条款',
  },
  {
    id: 15,
    stage: '融资',
    title: '怎么和联创分股份',
    url: 'https://ltse.com/insights/founders-guide-to-allocating-co-founder-equity',
    oneLiner: '别再51:49了',
    lang: 'en',
    insight: '标准vesting：4年+1年cliff。避免完全平分——投资人会觉得你们没做过艰难对话。',
    scene: '你和合伙人要分股权',
  },
  {
    id: 16,
    stage: '融资',
    title: 'Carta - SAFE 101',
    url: 'https://carta.com/learn/startups/fundraising/convertible-securities/safes/',
    oneLiner: 'SAFE完整解释，含post-money计算方法',
    lang: 'en',
    insight: 'SAFE的完整解释，包括post-money估值如何计算稀释。',
    scene: '你想理解SAFE的数学原理',
  },
  {
    id: 17,
    stage: '融资',
    title: 'Series A 估值',
    url: 'https://www.zeni.ai/blog/series-a-valuations',
    oneLiner: 'A轮估值怎么估（希望自己能到这一步）',
    lang: 'en',
    insight: '2026年Series A：需要$2-5M ARR，25%+月增长，median pre-money $45M。',
    scene: '你在准备A轮',
  },
  // ── 增长 ──
  {
    id: 18,
    stage: '增长',
    title: 'Founder Institute Benchmarks',
    url: 'https://fi.co/benchmarks',
    oneLiner: 'Pre-seed到Series A的revenue/users/growth对标，有很多25年的交易数据',
    lang: 'en',
    insight: '各阶段期望：pre-seed月增长15-20%，seed月增长15%，Series A月增长12%+。',
    scene: '你想知道你这个阶段应该达到什么增长率',
  },
  {
    id: 19,
    stage: '增长',
    title: 'Series A Crunch 数据',
    url: 'https://www.scaleup.finance/article/the-series-a-crunch-is-back-why-85-of-seed-stage-startups-now-fail-to-raise-series-a-and-how-to-beat-the-odds',
    oneLiner: '85%的seed拿不到A轮，间隔已拉到744天',
    lang: 'en',
    insight: '2022 seed cohort只有15.4%拿到A轮。Seed到A轮median间隔744天（2年+）。',
    scene: '你拿了seed轮，想知道拿到A轮的真实概率',
  },
  {
    id: 20,
    stage: '增长',
    title: 'Burn Rate 2025 指南',
    url: 'https://www.phoenixstrategy.group/blog/burn-rate-trends-investors-expect-2025',
    oneLiner: '投资人期望的burn multiple: <1.6x',
    lang: 'en',
    insight: 'Median burn multiple 1.6x。<1.0x=top 10%。>3.0x=危险。',
    scene: '你想知道自己的burn rate是否健康',
  },
  {
    id: 21,
    stage: '增长',
    title: 'Open Startup List',
    url: 'https://openstartuplist.com/',
    oneLiner: '公开收入数据的公司列表',
    lang: 'en',
    insight: '公开分享收入数据的创业公司列表，直接看真实MRR。',
    scene: '你想看真实公司的真实收入数据',
  },
  {
    id: 22,
    stage: '增长',
    title: 'TrustMRR',
    url: 'https://trustmrr.com/open',
    oneLiner: '经过Stripe验证的真实收入数据',
    lang: 'en',
    insight: '经过Stripe API验证的真实收入数据，不是自报数字。',
    scene: '你想看经过验证的真实startup收入',
  },
  {
    id: 23,
    stage: '增长',
    title: 'openboard.fyi',
    url: 'https://openboard.fyi/',
    oneLiner: '连接Stripe自动生成公开dashboard',
    lang: 'en',
    insight: '连接Stripe自动生成公开metrics dashboard，含MRR/ARR/churn/流量。',
    scene: '你想公开自己的数据或看别人的实时数据',
  },
  {
    id: 24,
    stage: '增长',
    title: 'Stripe 招人指南',
    url: 'https://stripe.com/resources/more/how-to-hire-the-first-employees-for-your-startup-a-guide-for-founders',
    oneLiner: 'Stripe出的招人指南',
    lang: 'en',
    insight: 'Stripe的创始人招人指南，含何时招/招什么角色/如何评估。',
    scene: '你准备招第一批员工',
  },
  {
    id: 25,
    stage: '增长',
    title: 'Lenny - Hiring Your Early Team',
    url: 'https://www.lennysnewsletter.com/p/hiring-your-early-team-b2b',
    oneLiner: '第1个/前3个/前10个员工分别怎么招',
    lang: 'en',
    insight: '67%的公司第一个员工是工程师。generalist比specialist更重要。',
    scene: '你在纠结第一个员工应该招什么角色',
  },
  {
    id: 26,
    stage: '增长',
    title: 'SaaS 定价指南 - Tomasz Tunguz',
    url: 'https://tomtunguz.com/pricing-guide/',
    oneLiner: 'VC视角的SaaS定价框架',
    lang: 'en',
    insight: '优化定价比获客有效4倍。企业客户会因为你定价太低而不信任你。',
    scene: '你在给产品定价',
  },
  // ── 失败/转向 ──
  {
    id: 27,
    stage: '失败/转向',
    title: 'CB Insights Post-Mortem',
    url: 'https://www.cbinsights.com/research/startup-failure-post-mortem/',
    oneLiner: '最大的创业失败案例库，按失败原因分类，23/24年的有点老',
    lang: 'en',
    insight: '483个失败案例，top原因：42%没有市场需求，29%现金耗尽，23%团队不对。',
    scene: '你想学习别人的失败',
  },
  {
    id: 28,
    stage: '失败/转向',
    title: 'Mercury - 3 Founders on Pivoting',
    url: 'https://mercury.com/blog/startup-pivot-stories-from-founders',
    oneLiner: '三个创始人的pivot真实决策过程',
    lang: 'en',
    insight: 'Jasper：做了18个月没traction的产品，从15人裁到5人，30天后发现AI方向后增长爆发。',
    scene: '你在考虑是否该pivot',
  },
  {
    id: 29,
    stage: '失败/转向',
    title: 'Lenny - The Art of the Pivot',
    url: 'https://www.lennysnewsletter.com/p/the-art-of-the-pivot-part-2-how-why',
    oneLiner: 'Pivot的时机/方法/信号',
    lang: 'en',
    insight: '什么时候该pivot，什么时候该坚持，具体的信号和方法论。',
    scene: '你不确定是该pivot还是该再坚持一下',
  },
  // ── 心态/思维模型 ──
  {
    id: 30,
    stage: '心态',
    title: 'Paul Graham - How Not to Die',
    url: 'https://paulgraham.com/die.html',
    oneLiner: '创业公司死因只有一个：创始人放弃',
    lang: 'en',
    insight: '大多数创业公司不是因为没钱死的，而是因为创始人心理崩溃。只要你不死就能成功。',
    scene: '你在考虑是否该放弃',
  },
  {
    id: 31,
    stage: '心态',
    title: 'Bezos 决策框架',
    url: 'https://www.leadingsapiens.com/bezos-on-failure-decision-making-life/',
    oneLiner: 'Type 1 vs Type 2决策/后悔最小化框架',
    lang: 'en',
    insight: '大多数决策是可逆的（Type 2），70%信息就该行动。等待不会降低风险。',
    scene: '你在一个重要决策上犹豫不决',
  },
  {
    id: 32,
    stage: '心态',
    title: 'First Round - 30 Best Advice 2024',
    url: 'https://review.firstround.com/the-30-best-pieces-of-company-building-advice-we-heard-in-2024/',
    oneLiner: '每年精选30条，已连续12年',
    lang: 'en',
    insight: '卡住了要做200%的调整不是10%。主动挖掘冲突比避免冲突更快。',
    scene: '你想快速获取一年中最好的创业建议',
  },
  {
    id: 33,
    stage: '心态',
    title: 'First Round - 第一次创业避坑指南',
    url: 'https://review.firstround.com/the-first-time-founders-guide-to-learning-everything-the-hard-way/',
    oneLiner: '第一次创业者的完整避坑指南',
    lang: 'en',
    insight: '五个隐藏陷阱：增长太快没理解为什么有效、被候选人忽悠、不把advisor当资源用、团队burnout恢复平均9个月、表面盈利掩盖烂的unit economics。',
    scene: '你是第一次创业',
  },
  {
    id: 34,
    stage: '心态',
    title: 'Brutal Truths Nobody Told You',
    url: 'https://medium.com/jupitrr/brutal-truths-about-startup-founders-that-nobody-told-you-6256196bcf40',
    oneLiner: '身份融合/孤独/和真实的心理代价',
    lang: 'en',
    insight: '创业最危险的时刻是你的身份和公司融为一体——之后每次挫折都是对你个人的否定。',
    scene: '你感到创业的心理压力很大',
  },
  {
    id: 35,
    stage: '心态',
    title: 'HN - I Don\'t Want to Be a Founder',
    url: 'https://news.ycombinator.com/item?id=23894387',
    oneLiner: '反面视角：为什么有人选择不创业',
    lang: 'en',
    insight: '一群有能力创业的人解释为什么选择不创业，提供重要的反面视角。',
    scene: '你在犹豫要不要创业',
  },
]

/** Look up a source by ID */
export function getSourceById(id: number): Source | undefined {
  return SOURCES.find((s) => s.id === id)
}

/** Get sources for a list of IDs */
export function getSourcesByIds(ids: readonly number[]): readonly Source[] {
  return ids
    .map((id) => SOURCES.find((s) => s.id === id))
    .filter((s): s is Source => s !== undefined)
}

/** Get all sources for a given stage */
export function getSourcesByStage(stage: string): readonly Source[] {
  return SOURCES.filter((s) => s.stage === stage)
}
