export interface Source {
  readonly id: number
  readonly stage: string
  readonly title: string
  readonly url: string
  readonly oneLiner: string
  readonly lang: 'en' | 'cn'
  readonly insight: string
  readonly scene: string
}

export const SOURCES: readonly Source[] = [
  {
    id: 1,
    stage: 'A. 想法 & 验证',
    title: 'Paul Graham - How to Get Startup Ideas',
    url: 'https://paulgraham.com/startupideas.html',
    oneLiner: '最经典的找想法方法论：从自己的问题出发',
    lang: 'en',
    insight: '好的创业想法不是想出来的，而是注意到的。刻意brainstorm会产生听起来合理但实际很差的想法。最好的想法来自创始人自己真实遇到的问题。',
    scene: '你正在试图"想一个创业点子"，列了一堆idea但都没有conviction',
  },
  {
    id: 2,
    stage: 'A. 想法 & 验证',
    title: 'Paul Graham - Do Things That Don\'t Scale',
    url: 'https://paulgraham.com/ds.html',
    oneLiner: '早期不需要规模化，手动服务10个用户',
    lang: 'en',
    insight: '不是产品要做得极好，而是用户体验要极好。早期手动做事（一个一个找用户、手动帮用户解决问题）不是偷懒，是唯一正确的方式。10%周增长4年后=200万用户。',
    scene: '你觉得\'手动做太慢了，要先把产品做好再推广\'',
  },
  {
    id: 3,
    stage: 'A. 想法 & 验证',
    title: 'Paul Graham - Startup = Growth',
    url: 'https://paulgraham.com/growth.html',
    oneLiner: '创业和小生意的唯一区别是增长率',
    lang: 'en',
    insight: '创业公司唯一要看的数字是增长率。YC标准：5-7%周增长=好，10%=优秀，1%=还没找到方向。5%周增长4年后月收入$25M，1%周增长同期只有$7900/月。',
    scene: '你不确定自己在做的是一个创业公司还是一个小生意',
  },
  {
    id: 4,
    stage: 'A. 想法 & 验证',
    title: 'Paul Graham 全部 Essays',
    url: 'https://paulgraham.com/articles.html',
    oneLiner: '200+篇 按时间排列 建议从最新的往回读',
    lang: 'en',
    insight: 'PG文章索引页 不需要单独提取洞察',
    scene: '目录/索引',
  },
  {
    id: 5,
    stage: 'A. 想法 & 验证',
    title: 'YC Request for Startups',
    url: 'https://www.ycombinator.com/rfs',
    oneLiner: 'YC 觉得什么问题值得做 每年更新',
    lang: 'en',
    insight: 'YC官方列出的他们认为值得解决的问题方向 每年更新',
    scene: '你在找方向 想知道什么问题足够大',
  },
  {
    id: 6,
    stage: 'A. 想法 & 验证',
    title: 'YC Spring 2026 RFS × Indie Hacker 视角',
    url: 'https://superframeworks.com/articles/yc-rfs-startup-ideas-indie-hackers-2026',
    oneLiner: 'YC 的8个方向中 独立开发者能做的部分',
    lang: 'en',
    insight: 'YC的8个方向拆解成独立开发者可以切入的具体产品形态',
    scene: '你是solo builder想知道YC的大方向里你能做什么',
  },
  {
    id: 7,
    stage: 'A. 想法 & 验证',
    title: 'Superhuman PMF Engine - Rahul Vohra',
    url: 'https://review.firstround.com/how-superhuman-built-an-engine-to-find-product-market-fit/',
    oneLiner: '如何量化 PMF：40%「非常失望」框架的原始出处',
    lang: 'en',
    insight: 'PMF可以量化：问用户\'如果明天不能用这个产品你多失望\'，40%说\'非常失望\'才算PMF。Superhuman用这个方法从22%拉到58%。四步法：细分用户→分析反馈→50/50路线图→持续追踪。',
    scene: '你有用户了但不确定是不是真的PMF',
  },
  {
    id: 8,
    stage: 'A. 想法 & 验证',
    title: 'Superhuman PMF Engine 可操作版 (Coda)',
    url: 'https://coda.io/@rahulvohra/superhuman-product-market-fit-engine',
    oneLiner: '上面那篇文章的实操模板 可以直接复制使用',
    lang: 'en',
    insight: 'Rahul Vohra PMF框架的可操作Coda模板 可以直接复制到自己项目用',
    scene: '你想立刻开始量化自己的PMF',
  },
  {
    id: 9,
    stage: 'A. 想法 & 验证',
    title: 'Lenny - Finding PMF in B2B',
    url: 'https://www.lennysnewsletter.com/p/finding-product-market-fit',
    oneLiner: '20+个成功 B2B 创始人的 PMF 故事',
    lang: 'en',
    insight: '20+个B2B创始人的真实PMF故事 含具体时间线和转折点',
    scene: '你在做B2B产品 想看别人怎么找到PMF的',
  },
  {
    id: 10,
    stage: 'A. 想法 & 验证',
    title: 'Lenny - How to Know If You\'ve Got PMF',
    url: 'https://www.lennysnewsletter.com/p/how-to-know-if-youve-got-productmarket',
    oneLiner: 'PMF 不是二元的 是一个光谱',
    lang: 'en',
    insight: 'PMF不是有或没有 是一个光谱。多个信号叠加才能判断：留存曲线、NPS、40%测试、有机增长比例',
    scene: '你觉得自己\'好像有PMF又好像没有\'',
  },
  {
    id: 11,
    stage: 'A. 想法 & 验证',
    title: 'Lenny - PMF Framework (Todd Jackson)',
    url: 'https://www.lennysnewsletter.com/p/a-framework-for-finding-product-market',
    oneLiner: 'First Round 的四步 PMF 框架 通常需要4-6年',
    lang: 'en',
    insight: 'First Round的数据：达到极致PMF通常需要4-6年。四步框架：假设→原型→MVP→规模化',
    scene: '你刚开始做 想知道PMF的合理时间预期',
  },
  {
    id: 12,
    stage: 'B. 从0到1',
    title: 'Sam Altman - Startup Playbook',
    url: 'https://playbook.samaltman.com/',
    oneLiner: '5000字浓缩创业全流程 从想法到规模化',
    lang: 'en',
    insight: '99%的创业公司死于自杀而不是谋杀。慢的创始人从来不会成功。不要过早招人——员工带来组织复杂度。关注留存而不是注册数。',
    scene: '你在做创业的整体规划 需要一个框架性的概览',
  },
  {
    id: 13,
    stage: 'B. 从0到1',
    title: 'How to Start a Startup (Stanford 课程)',
    url: 'https://startupclass.samaltman.com/',
    oneLiner: '20讲视频课 Sam Altman + PG + Peter Thiel 等',
    lang: 'en',
    insight: '斯坦福20讲视频课 涵盖想法/产品/增长/融资/团队',
    scene: '你想系统学习创业 愿意投入20小时看视频',
  },
  {
    id: 14,
    stage: 'B. 从0到1',
    title: 'YC Startup School 课程',
    url: 'https://www.startupschool.org/curriculum',
    oneLiner: '7周免费系统课程 YC 15年经验浓缩',
    lang: 'en',
    insight: '7周结构化课程 每周1-2小时 YC合伙人和成功创始人授课',
    scene: '你想要一个有节奏的学习路径而不是零散文章',
  },
  {
    id: 15,
    stage: 'B. 从0到1',
    title: 'YC Library（按主题搜索）',
    url: 'https://www.ycombinator.com/library',
    oneLiner: 'YC 全部内容 可按主题筛选',
    lang: 'en',
    insight: 'YC所有文章/视频/播客的统一搜索入口 按fundraising/product/growth等分类',
    scene: '你有一个具体问题想找YC的建议',
  },
  {
    id: 16,
    stage: 'B. 从0到1',
    title: 'indie-dev-toolkit (GitHub)',
    url: 'https://github.com/thedaviddias/indie-dev-toolkit',
    oneLiner: '独立开发者工具栈大全',
    lang: 'en',
    insight: '精选的独立开发者工具清单 从支付到部署到营销到分析全覆盖',
    scene: '你在选技术栈/工具 不想花时间逐个评估',
  },
  {
    id: 17,
    stage: 'B. 从0到1',
    title: 'Indie Hacker Tools 2025',
    url: 'https://www.builtthisweek.com/blog/indie-hacker-tools-2025',
    oneLiner: '2025最新工具推荐 AI + no-code 为主',
    lang: 'en',
    insight: '2025年最新的indie hacker工具推荐 侧重AI和no-code',
    scene: '你想知道现在solo builder都在用什么工具',
  },
  {
    id: 18,
    stage: 'B. 从0到1',
    title: 'Product Hunt 发布完整指南',
    url: 'https://www.demandcurve.com/playbooks/product-hunt-launch',
    oneLiner: 'Demand Curve 的 PH 发布实操手册',
    lang: 'en',
    insight: 'PH发布的完整操作手册 含时间线/准备清单/前3小时策略',
    scene: '你准备在Product Hunt上发布',
  },
  {
    id: 19,
    stage: 'B. 从0到1',
    title: 'PH Launch Checklist 2026',
    url: 'https://calmops.com/indie-hackers/product-hunt-launch-guide/',
    oneLiner: '最新版 PH 发布清单 含算法变化',
    lang: 'en',
    insight: '2026最新PH算法变化和发布策略',
    scene: '你想知道PH最新的规则和玩法',
  },
  {
    id: 20,
    stage: 'B. 从0到1',
    title: 'Indie Hackers vs Product Hunt 数据对比',
    url: 'https://awesome-directories.com/blog/indie-hackers-launch-strategy-guide-2025/',
    oneLiner: 'IH 转化率 23% vs PH 3%',
    lang: 'en',
    insight: 'IH帖子转化率23% vs PH发布转化率3%。最有效策略：先在IH建社区4-6个月 再在PH发布。分享真实收入数字的帖子效果最好。',
    scene: '你在纠结先发PH还是先在IH社区发帖',
  },
  {
    id: 21,
    stage: 'C. 融资 & 法律',
    title: 'YC SAFE 官方文档',
    url: 'https://www.ycombinator.com/documents',
    oneLiner: 'Post-money SAFE 模板 2025年90%的pre-seed用这个',
    lang: 'en',
    insight: 'YC官方SAFE文档 2025年Q1数据：90%的pre-seed和64%的seed用SAFE而不是priced round',
    scene: '你准备融资 需要法律文档模板',
  },
  {
    id: 22,
    stage: 'C. 融资 & 法律',
    title: 'Cooley GO SAFE 生成器',
    url: 'https://www.cooleygo.com/documents/y-combinator-safe-financing-document-generator/',
    oneLiner: '在线自动生成定制化 SAFE 文档 免费',
    lang: 'en',
    insight: '在线填写参数自动生成SAFE文档 支持US/UK/Singapore',
    scene: '你需要快速生成一份SAFE文档',
  },
  {
    id: 23,
    stage: 'C. 融资 & 法律',
    title: 'Startup Starter Pack (GitHub)',
    url: 'https://github.com/Ro5s/Startup-Starter-Pack',
    oneLiner: '开源法律文档合集',
    lang: 'en',
    insight: '开源法律文档：SAFE/Term Sheet/顾问协议/员工协议等',
    scene: '你需要各种创业法律文档模板',
  },
  {
    id: 24,
    stage: 'C. 融资 & 法律',
    title: 'Carta - Term Sheet 详解',
    url: 'https://carta.com/learn/startups/fundraising/term-sheets/',
    oneLiner: 'Term sheet 每一条都什么意思',
    lang: 'en',
    insight: 'Term sheet每一个条款的解释 从创始人视角说明哪些要警惕',
    scene: '你收到了term sheet但看不懂某些条款',
  },
  {
    id: 25,
    stage: 'C. 融资 & 法律',
    title: 'Carta - SAFE 101',
    url: 'https://carta.com/learn/startups/fundraising/convertible-securities/safes/',
    oneLiner: 'SAFE 完整解释 含 post-money 计算方法',
    lang: 'en',
    insight: 'SAFE的完整解释 包括post-money估值如何计算稀释',
    scene: '你想理解SAFE的数学原理',
  },
  {
    id: 26,
    stage: 'C. 融资 & 法律',
    title: 'Justin Kan - 股权分配指南',
    url: 'https://ltse.com/insights/founders-guide-to-allocating-co-founder-equity',
    oneLiner: 'Twitch 创始人写的合伙人股权分配实操',
    lang: 'en',
    insight: '股权分配：贡献相当就接近50/50 但避免完全平分（投资人会觉得你们没做过艰难对话）。标准vesting：4年+1年cliff',
    scene: '你和合伙人要分股权但不知道怎么分',
  },
  {
    id: 27,
    stage: 'C. 融资 & 法律',
    title: 'Seed 轮估值 2025 完整指南',
    url: 'https://www.flowjam.com/blog/seed-round-valuation-2025-complete-founders-guide',
    oneLiner: '2025 median pre-money $16M',
    lang: 'en',
    insight: '2025年seed轮median pre-money估值$16M 比去年涨19%',
    scene: '你在准备seed轮 想知道合理的估值范围',
  },
  {
    id: 28,
    stage: 'C. 融资 & 法律',
    title: 'Series A 估值 2026',
    url: 'https://www.zeni.ai/blog/series-a-valuations',
    oneLiner: '需要 $1-3M ARR + 15-20% 月增长',
    lang: 'en',
    insight: '2026年Series A：需要$2-5M ARR 25%+月增长 median pre-money $45M 平均融$16.6M',
    scene: '你在准备A轮 想知道投资人期望什么数字',
  },
  {
    id: 29,
    stage: 'D. 增长 & 基准数据',
    title: '2025 B2B SaaS Benchmarks',
    url: 'https://www.lightercapital.com/blog/2025-b2b-saas-startup-benchmarks',
    oneLiner: 'Churn/burn/ARR 各阶段基准数字 最全',
    lang: 'en',
    insight: '2025年SaaS基准：median revenue churn 12.5% 教育行业churn翻倍到22%',
    scene: '你想知道自己的churn/burn/ARR和行业平均比怎么样',
  },
  {
    id: 30,
    stage: 'D. 增长 & 基准数据',
    title: 'Founder Institute 各阶段基准',
    url: 'https://fi.co/benchmarks',
    oneLiner: 'Pre-seed 到 Series A 的 revenue/users/growth 对标',
    lang: 'en',
    insight: '各阶段期望：pre-seed月增长15-20% seed月增长15% Series A月增长12%+',
    scene: '你想知道你这个阶段应该达到什么增长率',
  },
  {
    id: 31,
    stage: 'D. 增长 & 基准数据',
    title: 'Series A Crunch 数据',
    url: 'https://www.scaleup.finance/article/the-series-a-crunch-is-back-why-85-of-seed-stage-startups-now-fail-to-raise-series-a-and-how-to-beat-the-odds',
    oneLiner: '85%的 seed 拿不到 A 轮 间隔已拉到744天',
    lang: 'en',
    insight: '2022 seed cohort只有15.4%拿到A轮（2018年是30.6%）。SaaS从37%降到12%。Seed到A轮median间隔744天（2年+）。A轮需要$2-5M ARR + Rule of 40。',
    scene: '你拿了seed轮 想知道拿到A轮的真实概率和时间线',
  },
  {
    id: 32,
    stage: 'D. 增长 & 基准数据',
    title: 'Burn Rate 2025 指南',
    url: 'https://www.phoenixstrategy.group/blog/burn-rate-trends-investors-expect-2025',
    oneLiner: '投资人期望的 burn multiple: <1.6x',
    lang: 'en',
    insight: 'Median burn multiple 1.6x（每赚$1花$1.60）。<1.0x=top 10%。>3.0x=危险。AI公司平均>2.5x。45%美国VC-backed公司月burn超$1M。',
    scene: '你想知道自己的burn rate是否健康',
  },
  {
    id: 33,
    stage: 'D. 增长 & 基准数据',
    title: 'Open Startup List',
    url: 'https://openstartuplist.com/',
    oneLiner: '公开收入数据的公司列表',
    lang: 'en',
    insight: '公开分享收入数据的创业公司列表 可以直接看真实MRR',
    scene: '你想看真实公司的真实收入数据',
  },
  {
    id: 34,
    stage: 'D. 增长 & 基准数据',
    title: 'TrustMRR（Stripe 验证收入）',
    url: 'https://trustmrr.com/open',
    oneLiner: '经过 Stripe 验证的真实收入数据',
    lang: 'en',
    insight: '经过Stripe API验证的真实收入数据 不是自报数字',
    scene: '你想看经过验证的真实startup收入',
  },
  {
    id: 35,
    stage: 'D. 增长 & 基准数据',
    title: 'openboard.fyi',
    url: 'https://openboard.fyi/',
    oneLiner: '连接 Stripe 自动生成公开 dashboard',
    lang: 'en',
    insight: '连接Stripe自动生成公开metrics dashboard 含MRR/ARR/churn/流量',
    scene: '你想公开自己的数据或看别人的实时数据',
  },
  {
    id: 36,
    stage: 'D. 增长 & 基准数据',
    title: 'Stripe - 如何招前10个员工',
    url: 'https://stripe.com/resources/more/how-to-hire-the-first-employees-for-your-startup-a-guide-for-founders',
    oneLiner: 'Stripe 出的招人指南',
    lang: 'en',
    insight: 'Stripe的创始人招人指南 含何时招/招什么角色/如何评估',
    scene: '你准备招第一批员工',
  },
  {
    id: 37,
    stage: 'D. 增长 & 基准数据',
    title: 'Lenny - Hiring Your Early Team',
    url: 'https://www.lennysnewsletter.com/p/hiring-your-early-team-b2b',
    oneLiner: '第1个/前3个/前10个员工分别怎么招',
    lang: 'en',
    insight: '67%的公司第一个员工是工程师。generalist比specialist更重要。从个人网络找人 不要用招聘平台。',
    scene: '你在纠结第一个员工应该招什么角色',
  },
  {
    id: 38,
    stage: 'D. 增长 & 基准数据',
    title: 'SaaS 定价完整指南 - Tomasz Tunguz',
    url: 'https://tomtunguz.com/pricing-guide/',
    oneLiner: 'VC 视角的 SaaS 定价框架',
    lang: 'en',
    insight: '定价不是数学题是销售题——\'selling price is a function of your ability to sell and nothing else\'。优化定价比获客有效4倍。企业客户会因为你定价太低而不信任你。usage-based定价销售周期长29%。',
    scene: '你在给产品定价 不知道该收多少钱',
  },
  {
    id: 39,
    stage: 'E. 失败 & 决策复盘',
    title: 'CB Insights - 483 个 Startup Post-Mortem',
    url: 'https://www.cbinsights.com/research/startup-failure-post-mortem/',
    oneLiner: '最大的创业失败案例库 按失败原因分类',
    lang: 'en',
    insight: '483个失败案例 top原因：42%没有市场需求 29%现金耗尽 23%团队不对 19%被竞争打败。很少只有一个原因。',
    scene: '你想学习别人的失败 避免同样的错误',
  },
  {
    id: 40,
    stage: 'E. 失败 & 决策复盘',
    title: 'Autopsy - 2000+ Post-Mortem',
    url: 'https://www.getautopsy.com/',
    oneLiner: '比 CB Insights 更大的可搜索失败案例数据库',
    lang: 'en',
    insight: '2000+创业失败案例 可按行业/阶段/失败原因搜索',
    scene: '你想找和自己类似领域的失败案例',
  },
  {
    id: 41,
    stage: 'E. 失败 & 决策复盘',
    title: 'Sahil Lavingia - Reflecting on My Failure',
    url: 'https://sahillavingia.com/reflecting',
    oneLiner: 'Gumroad：从 $350K/月 burn 到裁员75%到 $20M 收入0员工',
    lang: 'en',
    insight: '2015年6月：月收入$89K 月支出$364K 月亏$351K。裁员75%含最好的朋友。一年后：月收入$176K 支出$32K 月赚$10K。最终：$20.7M年收入 $8.9M利润 0个全职员工。核心教训：市场决定增长 不是产品。',
    scene: '你在纠结是否该继续追求VC规模还是做一个可持续的小公司',
  },
  {
    id: 42,
    stage: 'E. 失败 & 决策复盘',
    title: 'Groove - How Our Startup Almost Died',
    url: 'https://www.groovehq.com/blog/how-our-startup-almost-died',
    oneLiner: '最详细的 near-death 复盘 含具体心理过程',
    lang: 'en',
    insight: '创始人对导师说：\'We\'re dying。\'犯了最大的罪：花6个月做了自己假设人们想要的产品。烧光了大部分现金 零traction。转折点：停下一切 找40个人请教 发现了之前完全忽略的领域。绝望逼出了诚实。',
    scene: '你的产品没有traction 现金在减少 你在考虑是否该放弃',
  },
  {
    id: 43,
    stage: 'E. 失败 & 决策复盘',
    title: 'Groove - Rescuing Startup from Death',
    url: 'https://www.groovehq.com/blog/rescuing-startup-death',
    oneLiner: '上面那篇的续集：具体怎么救回来的',
    lang: 'en',
    insight: 'Groove如何从濒死状态恢复的具体操作步骤',
    scene: '你想知道从near-death恢复的具体方法',
  },
  {
    id: 44,
    stage: 'E. 失败 & 决策复盘',
    title: 'Fibery - Startups and Near-Death Experience',
    url: 'https://fibery.com/blog/essays/startups-and-near-death-experience/',
    oneLiner: 'Near-death 反而是转折点的规律分析',
    lang: 'en',
    insight: '很多顶级startup都经历过near-death 这反而成为转折点——因为逼迫创始人做出之前不敢做的决定',
    scene: '你的公司正在经历危机 你不确定这是终点还是转折点',
  },
  {
    id: 45,
    stage: 'E. 失败 & 决策复盘',
    title: 'AppDynamics - Why I Regret Selling for $3.7B',
    url: 'https://www.cnbc.com/2024/09/30/appdynamics-founder-why-i-regret-selling-my-startup-for-billions.html',
    oneLiner: '卖掉公司后又创办了同等估值的新公司',
    lang: 'en',
    insight: '以$3.7B卖给Cisco后后悔了——发现自己真正享受的是building的过程。6个月旅行后创办Harness 估值也到$3.7B。核心教训：卖掉的后悔率远高于想象。',
    scene: '你在考虑是否该接受收购offer',
  },
  {
    id: 46,
    stage: 'E. 失败 & 决策复盘',
    title: 'Mercury - 3 Founders on Pivoting',
    url: 'https://mercury.com/blog/startup-pivot-stories-from-founders',
    oneLiner: '三个创始人的 pivot 真实决策过程',
    lang: 'en',
    insight: 'Jasper：做了18个月没traction的产品 从15人裁到5人 30天后发现AI方向后增长爆发。Curio：从DTC wellness转到正式医疗服务 所有指标都变好了。Fuse：B2C转B2B 客户主动要求用他们的内部系统。',
    scene: '你在考虑是否该pivot 不确定什么信号说明该转',
  },
  {
    id: 47,
    stage: 'E. 失败 & 决策复盘',
    title: 'Lenny - The Art of the Pivot',
    url: 'https://www.lennysnewsletter.com/p/the-art-of-the-pivot-part-2-how-why',
    oneLiner: 'Pivot 的时机/方法/信号',
    lang: 'en',
    insight: '什么时候该pivot 什么时候该坚持 具体的信号和方法论',
    scene: '你不确定是该pivot还是该再坚持一下',
  },
  {
    id: 48,
    stage: 'F. 思维模型 & 心态',
    title: 'Paul Graham - How Not to Die',
    url: 'https://paulgraham.com/die.html',
    oneLiner: '创业公司死因只有一个：创始人放弃',
    lang: 'en',
    insight: '大多数创业公司不是因为没钱死的 而是因为创始人心理崩溃。\'只要你不死就能成功。\'外部accountability是最有效的续命机制——公开承诺让人不好意思放弃。',
    scene: '你在考虑是否该放弃',
  },
  {
    id: 49,
    stage: 'F. 思维模型 & 心态',
    title: 'NFX - Startup Mental Models Part 1',
    url: 'https://www.nfx.com/post/mental-models-part-one',
    oneLiner: '创业是终极心理游戏 具体思维模型',
    lang: 'en',
    insight: '创业特定的思维模型集合 包括网络效应/市场时机/防御性等',
    scene: '你想建立更系统的创业决策框架',
  },
  {
    id: 50,
    stage: 'F. 思维模型 & 心态',
    title: 'Bezos 全部决策框架',
    url: 'https://www.leadingsapiens.com/bezos-on-failure-decision-making-life/',
    oneLiner: 'Type 1 vs Type 2 决策/后悔最小化框架',
    lang: 'en',
    insight: 'Type 1=不可逆决策（慢慢想）Type 2=可逆决策（快速决定）。大多数决策是Type 2但公司会把所有决策都当Type 1导致致命的慢。70%信息就该决策。后悔最小化：80岁回头看会后悔没做什么？',
    scene: '你在一个重要决策上犹豫不决',
  },
  {
    id: 51,
    stage: 'F. 思维模型 & 心态',
    title: 'First Round - 30 Best Advice 2024',
    url: 'https://review.firstround.com/the-30-best-pieces-of-company-building-advice-we-heard-in-2024/',
    oneLiner: '每年精选30条 已连续12年',
    lang: 'en',
    insight: '卡住了要做200%的调整不是10%。主动\'挖掘冲突\'比避免冲突更快。客户抱怨=说明你的产品已经不可或缺。只在痛到不行时才招人。距离比死磕更能解决问题。',
    scene: '你想快速获取一年中最好的创业建议',
  },
  {
    id: 52,
    stage: 'F. 思维模型 & 心态',
    title: 'First Round - Must Reads 全集',
    url: 'https://review.firstround.com/articles/must-reads/',
    oneLiner: 'First Round Review 历史最高阅读量文章',
    lang: 'en',
    insight: 'First Round Review 2013年以来阅读量最高的文章合集',
    scene: '你想读FR最经典的文章',
  },
  {
    id: 53,
    stage: 'F. 思维模型 & 心态',
    title: 'First Round - First-Time Founder Guide',
    url: 'https://review.firstround.com/the-first-time-founders-guide-to-learning-everything-the-hard-way/',
    oneLiner: '第一次创业者的完整避坑指南',
    lang: 'en',
    insight: '五个隐藏陷阱：1)增长太快没理解为什么有效 2)被不懂的领域的候选人忽悠 3)不把advisor当真正的资源用 4)团队burnout平均恢复9个月 5)表面盈利掩盖了烂的unit economics（Drop在$100M收入时才发现）',
    scene: '你是第一次创业 想知道最容易踩的坑',
  },
  {
    id: 54,
    stage: 'F. 思维模型 & 心态',
    title: 'Brutal Truths Nobody Told You',
    url: 'https://medium.com/jupitrr/brutal-truths-about-startup-founders-that-nobody-told-you-6256196bcf40',
    oneLiner: '身份融合/孤独/和真实的心理代价',
    lang: 'en',
    insight: '创业最危险的时刻是你的身份和公司融为一体——之后每次挫折都是对你个人的否定。Solo founder极度孤独。大部分真实挣扎被从公开叙事中删除了。',
    scene: '你感到创业的心理压力很大但觉得不应该说出来',
  },
  {
    id: 55,
    stage: 'F. 思维模型 & 心态',
    title: 'HN - I Don\'t Want to Be a Founder',
    url: 'https://news.ycombinator.com/item?id=23894387',
    oneLiner: '反面视角：为什么有人选择不创业',
    lang: 'en',
    insight: '一群有能力创业的人解释为什么选择不创业 提供了重要的反面视角',
    scene: '你在犹豫要不要创业 想听听选择不创业的人怎么想',
  },
  {
    id: 56,
    stage: 'G. 中文生态',
    title: '中国独立开发者生存现状 2025',
    url: 'https://blog.csdn.net/FansUnion/article/details/148829546',
    oneLiner: '5%月入5万+/15%月入<3000 真实分层',
    lang: 'cn',
    insight: '1000+开发者调研：顶尖5%月入5万+ 稳定层30%月入8K-1.5W 挣扎层15%月入<3K。技术外包占收入40%。商业化能力比技术能力更稀缺——月入1.5万+的只有20%。有娃家庭一线城市需月入1.2万+。',
    scene: '你想做独立开发者但不知道真实的收入预期',
  },
  {
    id: 57,
    stage: 'G. 中文生态',
    title: 'Marc Lou 年入103万美元拆解',
    url: 'https://news.qq.com/rain/a/20260107A07ECX00',
    oneLiner: '25个项目做了12个赚钱的 成功率48%',
    lang: 'cn',
    insight: '一个人做了25个项目 12个赚钱 没有融资没有团队没有办公室 年入103万美元',
    scene: '你想看一个solo builder的极限收入和方法论',
  },
  {
    id: 58,
    stage: 'G. 中文生态',
    title: '阿小信 - 2025年度总结',
    url: 'https://blog.axiaoxin.com/post/2025-summary/',
    oneLiner: '自由职业第二年收入+62% 含至暗时刻细节',
    lang: 'cn',
    insight: '收入同比+62%但经历三大危机：AdSense账号被停（一周零收入）、被监管约谈两次、血压飙升。核心认知：\'赚钱应该是为了让自己快乐 而不是对吃屎的补偿。\'从\'求生\'转向\'扎根\'。',
    scene: '你是独立开发者 想看真实的年度复盘含低谷',
  },
  {
    id: 59,
    stage: 'G. 中文生态',
    title: '独立开发者书单 2025',
    url: 'https://www.ixiqin.com/2025/12/13/book-list-of-indiehacker/',
    oneLiner: '中文独立开发者推荐书单',
    lang: 'cn',
    insight: '中文独立开发者精选书单 帮助快速上手和避免基础错误',
    scene: '你想系统学习独立开发 偏好中文书',
  },
  {
    id: 60,
    stage: 'G. 中文生态',
    title: '独立开发工具半月刊',
    url: 'https://www.cnblogs.com/leadingcode/p/18930982',
    oneLiner: '中文定期更新的开发者工具推荐',
    lang: 'cn',
    insight: '中文定期更新的独立开发者工具和资源推荐',
    scene: '你想跟踪中文生态的最新工具',
  },
  {
    id: 61,
    stage: 'G. 中文生态',
    title: 'W2Solo - 中文独立开发者社区',
    url: 'https://w2solo.com/',
    oneLiner: '中文版 Indie Hackers',
    lang: 'cn',
    insight: '中文独立开发者社区 可以看真实案例和讨论',
    scene: '你想加入中文的独立开发者社区',
  },
  {
    id: 62,
    stage: 'G. 中文生态',
    title: '即刻 独立开发者社区',
    url: 'https://x.com/i/communities/1503688305988169728',
    oneLiner: '活跃的中文 builder 讨论',
    lang: 'cn',
    insight: '即刻上活跃的中文builder社区',
    scene: '你想在中文社交媒体上找builder同行',
  },
  {
    id: 63,
    stage: 'H. 持续信息源',
    title: 'Lenny\'s Newsletter',
    url: 'https://www.lennysnewsletter.com/',
    oneLiner: '产品/增长/PMF 最高质量的 founder newsletter',
    lang: 'en',
    insight: '产品/增长/PMF领域最高质量的newsletter 含大量创始人访谈和框架',
    scene: '你想订阅一个高质量的创业newsletter',
  },
  {
    id: 64,
    stage: 'H. 持续信息源',
    title: 'First Round Review',
    url: 'https://review.firstround.com/',
    oneLiner: '深度创业文章 每篇3000+字精品',
    lang: 'en',
    insight: '每篇3000+字的深度创业文章 来自First Round投资组合的真实经验',
    scene: '你想读深度的创业长文而不是碎片化建议',
  },
  {
    id: 65,
    stage: 'H. 持续信息源',
    title: 'Indie Hackers',
    url: 'https://www.indiehackers.com/',
    oneLiner: 'Builder 社区 + 真实收入数据 + 创业故事',
    lang: 'en',
    insight: 'Builder社区 可以看真实收入数据和创业故事 参与讨论',
    scene: '你想加入英文的独立builder社区',
  },
  {
    id: 66,
    stage: 'H. 持续信息源',
    title: 'Dalton & Michael Podcast',
    url: 'https://open.spotify.com/show/6a0FlIaYgSu9JKZI4HfyNl',
    oneLiner: 'YC 合伙人的创业 podcast 短且实用',
    lang: 'en',
    insight: 'YC合伙人的podcast 每期15-30分钟 实用且直接',
    scene: '你想听短且实用的创业podcast',
  },
  {
    id: 67,
    stage: 'H. 持续信息源',
    title: 'How I Built This',
    url: 'https://www.npr.org/series/490248027/how-i-built-this',
    oneLiner: '700+期 每期一个公司从0到1的完整故事',
    lang: 'en',
    insight: '700+个公司从0到1的完整故事 用创始人自己的话讲述',
    scene: '你想听真实的创业故事获取灵感',
  },
  {
    id: 68,
    stage: 'H. 持续信息源',
    title: 'Masters of Scale (Reid Hoffman)',
    url: 'https://mastersofscale.com/',
    oneLiner: 'LinkedIn 创始人对话顶级创业者',
    lang: 'en',
    insight: 'Reid Hoffman对话顶级创业者 侧重规模化阶段的决策',
    scene: '你想了解公司从小到大的规模化决策',
  },
  {
    id: 69,
    stage: 'H. 持续信息源',
    title: 'YC Startup Library / Carousel',
    url: 'https://www.ycombinator.com/library/carousel/Essays%20by%20Paul%20Graham',
    oneLiner: 'YC 所有内容的统一入口',
    lang: 'en',
    insight: 'YC全部内容的统一入口 含PG essays和所有YC视频',
    scene: '你想从YC的内容库开始浏览',
  },
] as const

export function getSourcesByStage(stage: string): readonly Source[] {
  return SOURCES.filter((s) => s.stage === stage)
}

export function getSourcesByIds(ids: readonly number[]): readonly Source[] {
  const idSet = new Set(ids)
  return SOURCES.filter((s) => idSet.has(s.id))
}

export function getSourcesByLang(lang: 'en' | 'cn'): readonly Source[] {
  return SOURCES.filter((s) => s.lang === lang)
}
